(function(){
 if(!/\/today\/?(?:index\.html)?$/.test(location.pathname)) return;
 const state={assessments:null,evidence:null};
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function hrefFor(e){if(e.url)return e.url;if(e.doi)return 'https://doi.org/'+encodeURIComponent(e.doi);if(e.pmid)return 'https://pubmed.ncbi.nlm.nih.gov/'+encodeURIComponent(e.pmid)+'/';return ''}
 function labelType(t){return ({peer_reviewed:'동료심사 논문',field_observation_paper:'현장 관찰 논문',specialist_group_species_account:'전문가 종 계정',specialist_husbandry:'전문 사육자료',specialist_veterinary_review:'전문 수의학 자료',specialist_plant_database:'전문 식물 DB',official_database:'공식 DB',official_agriculture_database:'공식 농업 DB',official_biodiversity_agriculture:'공공 생물·농업 DB',conference_proceedings:'학술대회 자료',peer_reviewed_context:'동료심사 문헌 맥락'}[t]||t||'출처')}
 function plantIdFrom(details){const a=details.querySelector('a[href*="../plant/"]');if(!a)return'';const m=a.getAttribute('href').match(/\.\.\/plant\/([^/]+)\//);return m?decodeURIComponent(m[1]):''}
 function renderSource(e){const href=hrefFor(e),tax=e.taxon?' · '+esc(e.taxon):'';return '<div class="source-preview-item"><b>'+esc(labelType(e.type))+tax+'</b><div>'+esc(e.citation||e.id)+'</div>'+(e.note?'<div class="source-note">'+esc(e.note)+'</div>':'')+(href?'<a href="'+esc(href)+'" target="_blank" rel="noopener noreferrer">원문/식별자 열기 ↗</a>':'')+'</div>'}
 function enhanceOne(details){if(details.dataset.sourcePreview==='1'||!state.assessments||!state.evidence)return;const id=plantIdFrom(details);if(!id)return;const a=state.assessments.find(x=>x.plant_id===id && Array.isArray(x.evidence_ids));if(!a)return;const srcs=a.evidence_ids.map(eid=>state.evidence.find(e=>e.id===eid)).filter(Boolean).slice(0,2);const box=document.createElement('div');box.className='source-preview';box.innerHTML='<div class="source-preview-title"><b>대표 출처 미리보기</b><span> · 최대 2개</span></div>'+(srcs.length?srcs.map(renderSource).join(''):'<div class="source-note">연결된 공개 출처 메타데이터 없음</div>')+'<div class="source-note">이 미리보기는 판정에 연결된 출처를 보여줄 뿐, 출처 1~2개만으로 전체 판정을 재계산하지 않는다.</div>';details.appendChild(box);details.dataset.sourcePreview='1'}
 function enhanceAll(){document.querySelectorAll('details.evidence').forEach(enhanceOne)}
 function addStyle(){if(document.getElementById('source-preview-style'))return;const s=document.createElement('style');s.id='source-preview-style';s.textContent='.source-preview{margin-top:10px;padding-top:8px;border-top:1px dashed #ccd9cf}.source-preview-title{font-size:13px;margin-bottom:6px}.source-preview-title span,.source-note{font-size:12px;color:#657067}.source-preview-item{padding:7px 0;border-top:1px solid #edf1ed;font-size:12px}.source-preview-item:first-of-type{border-top:0}.source-preview-item a{display:inline-block;margin-top:4px;font-weight:700}.source-preview-item b{font-size:12px}';document.head.appendChild(s)}
 Promise.all([fetch('../data/assessments.json').then(r=>r.json()),fetch('../data/evidence.json').then(r=>r.json())]).then(([a,e])=>{state.assessments=Array.isArray(a)?a:[];state.evidence=Array.isArray(e)?e:[];addStyle();enhanceAll();new MutationObserver(enhanceAll).observe(document.body,{childList:true,subtree:true})}).catch(()=>{});
})();
