(function(){
 if(!/\/today\/?(?:index\.html)?$/.test(location.pathname)) return;
 const state={assessments:null,evidence:null,mode:'all',candidateMode:'all',summarySig:''};
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function hrefFor(e){if(e.url)return e.url;if(e.doi)return 'https://doi.org/'+encodeURIComponent(e.doi);if(e.pmid)return 'https://pubmed.ncbi.nlm.nih.gov/'+encodeURIComponent(e.pmid)+'/';return ''}
 function labelType(t){return ({peer_reviewed:'동료심사 논문',field_observation_paper:'현장 관찰 논문',specialist_group_species_account:'전문가 종 계정',specialist_husbandry:'전문 사육자료',specialist_veterinary_review:'전문 수의학 자료',specialist_plant_database:'전문 식물 DB',official_database:'공식 DB',official_agriculture_database:'공식 농업 DB',official_biodiversity_agriculture:'공공 생물·농업 DB',conference_proceedings:'학술대회 자료',peer_reviewed_context:'동료심사 문헌 맥락'}[t]||t||'출처')}
 function isIberaPrimary(e){return e?.scope==='subspecies_direct_wild_diet'&&/Testudo graeca ibera/i.test(e?.taxon||'')}
 function isIberaSynthesis(e){return e?.scope==='subspecies_direct_diet_synthesis'&&/Testudo graeca ibera/i.test(e?.taxon||'')}
 function applicabilityBadge(e){const s=e.scope||'';if(isIberaPrimary(e))return['적용','이베라 직접 야생근거','direct'];if(isIberaSynthesis(e))return['적용','이베라 종계정 종합','direct'];if(s==='species_direct'||s==='species_diet_context')return['적용','다른 Testudo 직접·맥락','near'];if(s==='genus_husbandry'||s==='Mediterranean_Testudo')return['적용','Testudo·지중해 사육근거','near'];if(s==='plant_identity'||s==='plant_identity_context')return['적용','식물동정 근거','identity'];if(s==='nutrition')return['적용','영양성분 자료','nutrition'];if(e.type==='specialist_husbandry'||e.type==='specialist_veterinary_review'||e.type==='specialist_plant_database')return['적용','전문 사육·식물 근거','specialist'];return['적용','간접·일반 근거','general']}
 function qualityBadge(e){if(['peer_reviewed','field_observation_paper','peer_reviewed_context'].includes(e.type))return['출처','학술문헌','q1'];if(e.type==='specialist_group_species_account')return['출처','전문가 종 계정','q1'];if(['official_database','official_agriculture_database','official_biodiversity_agriculture'].includes(e.type))return['출처','공식·공공 DB','q2'];if(['specialist_husbandry','specialist_veterinary_review','specialist_plant_database'].includes(e.type))return['출처','전문기관 자료','q2'];if(e.type==='conference_proceedings')return['출처','학술대회 자료','q3'];return['출처','기타 출처','q3']}
 function badgeHTML(b){return '<span class="source-badge '+esc(b[2])+'"><span>'+esc(b[0])+'</span> '+esc(b[1])+'</span>'}
 function plantIdFrom(details){const a=details.querySelector('a[href*="../plant/"]');if(!a)return'';const m=a.getAttribute('href').match(/\.\.\/plant\/([^/]+)\//);return m?decodeURIComponent(m[1]):''}
 function assessmentFor(id){return state.assessments.find(x=>x.plant_id===id&&Array.isArray(x.evidence_ids))}
 function linkedEvidence(a){return (a?.evidence_ids||[]).map(eid=>state.evidence.find(e=>e.id===eid)).filter(Boolean)}
 function evidenceClass(a){const ev=linkedEvidence(a);if(ev.some(isIberaPrimary))return'primary';if(ev.some(isIberaSynthesis))return'synthesis';return'none'}
 function renderSource(e){const href=hrefFor(e),tax=e.taxon?' · '+esc(e.taxon):'',badges=badgeHTML(applicabilityBadge(e))+badgeHTML(qualityBadge(e));return '<div class="source-preview-item"><div class="source-badges">'+badges+'</div><b>'+esc(labelType(e.type))+tax+'</b><div>'+esc(e.citation||e.id)+'</div>'+(e.note?'<div class="source-note">'+esc(e.note)+'</div>':'')+(href?'<a href="'+esc(href)+'" target="_blank" rel="noopener noreferrer">원문/식별자 열기 ↗</a>':'')+'</div>'}
 function matchesMode(e){if(state.mode==='ibera')return isIberaPrimary(e);if(state.mode==='quality')return qualityBadge(e)[2]==='q1'||['official_database','official_agriculture_database','official_biodiversity_agriculture'].includes(e.type);return true}
 function sourcesFor(a){return linkedEvidence(a).filter(matchesMode).slice(0,2)}
 function fillBox(box,a){const srcs=sourcesFor(a),modeText=state.mode==='ibera'?'이베라 1차 직접근거':state.mode==='quality'?'학술·공식 출처':'전체 출처';box.innerHTML='<div class="source-preview-title"><b>대표 출처 미리보기</b><span> · '+esc(modeText)+' · 최대 2개</span></div>'+(srcs.length?srcs.map(renderSource).join(''):'<div class="source-note">현재 필터에 맞는 연결 출처 없음</div>')+'<div class="source-note">연결 출처가 없다는 사실은 부적합 판정을 뜻하지 않는다. 필터는 출처 표시만 좁히며 식물 판정·후보 순위·급여량·영양완전성을 다시 계산하지 않는다.</div>'}
 function enhanceOne(details){const id=plantIdFrom(details);if(!id||!state.assessments||!state.evidence)return;const a=assessmentFor(id);if(!a)return;let box=details.querySelector(':scope > .source-preview');if(!box){box=document.createElement('div');box.className='source-preview';details.appendChild(box)}fillBox(box,a);details.dataset.sourcePreview='1'}
 function badgeCandidate(label){if(label.dataset.directEvidenceBadge==='1')return;const details=label.querySelector('details.evidence'),id=details?plantIdFrom(details):'';if(!id)return;const a=assessmentFor(id),kind=evidenceClass(a),host=label.querySelector('div');if(!host)return;const tag=document.createElement('span');tag.className='tag direct-evidence '+kind;tag.textContent=kind==='primary'?'이베라 1차 직접근거 있음':kind==='synthesis'?'이베라 종계정 종합근거 있음':'이베라 1차 직접근거 미연결';host.insertBefore(tag,host.querySelector('.small')||details||null);label.dataset.directEvidenceBadge='1'}
 function isIberaProfile(){return window.TFDProfiles?.active?.()?.species==='ibera'}
 function candidateKind(label){const d=label.querySelector('details.evidence'),id=d?plantIdFrom(d):'';return evidenceClass(assessmentFor(id))}
 function syncCandidateControl(){const cb=document.getElementById('directCandidateOnly');if(!cb)return;const ok=isIberaProfile();cb.disabled=!ok;if(!ok&&cb.checked){cb.checked=false;state.candidateMode='all'}const note=document.getElementById('direct-candidate-control-note');if(note)note.textContent=ok?'현재 후보 중 이베라 1차 야생섭식 직접근거가 연결된 식물만 화면에 남긴다. 기본값은 전체 보기다.':'이 토글은 이베라(Testudo graeca ibera) 프로필에서만 사용한다.'}
 function applyCandidateFilter(){const labels=[...document.querySelectorAll('#candidates label.candidate')];const primaryOnly=state.candidateMode==='primary'&&isIberaProfile();let visible=0;labels.forEach(label=>{const show=!primaryOnly||candidateKind(label)==='primary';label.hidden=!show;if(show){visible++;return}const cb=label.querySelector('input[type="checkbox"][data-id]');if(cb?.checked){cb.checked=false;cb.dispatchEvent(new Event('change',{bubbles:true}))}});let empty=document.getElementById('direct-candidate-empty');if(primaryOnly&&labels.length&&visible===0){if(!empty){empty=document.createElement('div');empty.id='direct-candidate-empty';empty.className='card';document.getElementById('candidates')?.appendChild(empty)}empty.innerHTML='<b>이베라 1차 직접근거가 연결된 후보가 현재 목록에 없다.</b><div class="small">직접근거 미연결은 위험·부적합을 뜻하지 않는다. 토글을 끄면 전체 후보를 다시 볼 수 있다.</div>'}else if(empty)empty.remove()}
 function updateSummary(){const all=[...document.querySelectorAll('#candidates label.candidate')],labels=all.filter(x=>!x.hidden);if(!all.length){const old=document.getElementById('direct-evidence-summary');if(old)old.remove();state.summarySig='';return}const stats={primary:0,synthesis:0,none:0};labels.forEach(label=>stats[candidateKind(label)]++);const sig=all.length+'|'+labels.length+'|'+stats.primary+'|'+stats.synthesis+'|'+stats.none+'|'+state.candidateMode;if(sig===state.summarySig)return;state.summarySig=sig;let box=document.getElementById('direct-evidence-summary');if(!box){box=document.createElement('div');box.id='direct-evidence-summary';box.className='card evidence-summary';const c=document.getElementById('candidates');c?.insertAdjacentElement('beforebegin',box)}if(box)box.innerHTML='<b>후보 근거 한눈에 보기</b><div class="small">표시 후보 '+labels.length+'종 / 전체 후보 '+all.length+'종</div><div class="summary-grid"><span><strong>'+stats.primary+'</strong><small>이베라 1차 직접근거 연결</small></span><span><strong>'+stats.synthesis+'</strong><small>이베라 종계정 종합근거만 연결</small></span><span><strong>'+stats.none+'</strong><small>이베라 1차 직접근거 미연결</small></span></div><div class="small">현재 화면에 표시된 후보 기준이다. ‘미연결’은 위험하거나 부적합하다는 뜻이 아니라, 현재 DB에 이베라 1차 직접근거가 연결되어 있지 않다는 뜻이다.</div>'}
 function enhanceAll(){document.querySelectorAll('details.evidence').forEach(enhanceOne);document.querySelectorAll('#candidates label.candidate').forEach(badgeCandidate);syncCandidateControl();applyCandidateFilter();updateSummary()}
 function addControls(){if(document.getElementById('source-filter-card'))return;const scope=document.getElementById('scope');if(!scope)return;const card=document.createElement('div');card.id='source-filter-card';card.className='card';card.innerHTML='<b>근거 출처 필터</b><div class="source-filter-row"><button type="button" data-source-mode="all" class="source-filter active">전체</button><button type="button" data-source-mode="ibera" class="source-filter">이베라 1차 직접근거만</button><button type="button" data-source-mode="quality" class="source-filter">학술·공식근거만</button></div><div class="small">출처 표시 범위만 바꾼다. 식물 판정과 오늘 후보 순위는 바꾸지 않는다.</div><label class="candidate-filter-toggle"><input id="directCandidateOnly" type="checkbox"> <span><b>이베라 1차 직접근거 있는 후보만 보기</b><br><span id="direct-candidate-control-note" class="small">기본값은 전체 보기다.</span></span></label>';scope.insertAdjacentElement('afterend',card);card.querySelectorAll('[data-source-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.sourceMode;card.querySelectorAll('[data-source-mode]').forEach(x=>x.classList.toggle('active',x===b));enhanceAll()});const cb=card.querySelector('#directCandidateOnly');cb.onchange=()=>{state.candidateMode=cb.checked?'primary':'all';applyCandidateFilter();state.summarySig='';updateSummary()};syncCandidateControl()}
 function addStyle(){if(document.getElementById('source-preview-style'))return;const s=document.createElement('style');s.id='source-preview-style';s.textContent='.source-preview{margin-top:10px;padding-top:8px;border-top:1px dashed #ccd9cf}.source-preview-title{font-size:13px;margin-bottom:6px}.source-preview-title span,.source-note{font-size:12px;color:#657067}.source-preview-item{padding:8px 0;border-top:1px solid #edf1ed;font-size:12px}.source-preview-item:first-of-type{border-top:0}.source-preview-item a{display:inline-block;margin-top:4px;font-weight:700}.source-preview-item b{font-size:12px}.source-badges{display:flex;gap:5px;flex-wrap:wrap;margin-bottom:5px}.source-badge{display:inline-flex;gap:4px;align-items:center;border:1px solid #d7e0d8;border-radius:999px;padding:2px 7px;font-size:11px;font-weight:800;background:#fff}.source-badge span{font-weight:600;color:#657067}.source-badge.direct{background:#e6f5e9}.source-badge.near,.source-badge.specialist{background:#eef4ff}.source-badge.identity{background:#f4efff}.source-badge.nutrition{background:#fff4e5}.source-badge.general,.source-badge.q3{background:#f5f5f5}.source-badge.q1{background:#eaf7ef}.source-badge.q2{background:#f1f6ff}.source-filter-row{display:flex;gap:6px;flex-wrap:wrap;margin:9px 0}.source-filter{border:1px solid #d7e0d8;background:#fff;border-radius:999px;padding:7px 10px;min-height:36px;font-size:12px;font-weight:800}.source-filter.active{background:#2f6b49;color:#fff;border-color:#2f6b49}.candidate-filter-toggle{display:flex;gap:8px;align-items:flex-start;margin-top:12px;padding-top:10px;border-top:1px dashed #d7e0d8}.candidate-filter-toggle input{width:20px;height:20px;margin-top:2px}.candidate-filter-toggle input:disabled{opacity:.45}.direct-evidence.primary{background:#e6f5e9;border-color:#a8cfb3}.direct-evidence.synthesis{background:#eef4ff;border-color:#b9cceb}.direct-evidence.none{background:#f4f4f4;color:#5d675f}.evidence-summary{border:2px solid #c9ddce}.summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0}.summary-grid span{border:1px solid #dce5dd;border-radius:12px;padding:10px;background:#fafcf9;text-align:center}.summary-grid strong{display:block;font-size:22px}.summary-grid small{display:block;color:#657067;font-size:11px;line-height:1.35}#candidates label.candidate[hidden]{display:none!important}@media(max-width:560px){.summary-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
 Promise.all([fetch('../data/assessments.json').then(r=>r.json()),fetch('../data/evidence.json').then(r=>r.json())]).then(([a,e])=>{state.assessments=Array.isArray(a)?a:[];state.evidence=Array.isArray(e)?e:[];addStyle();addControls();enhanceAll();new MutationObserver(()=>{addControls();enhanceAll()}).observe(document.body,{childList:true,subtree:true})}).catch(()=>{});
})();
