(function(){
 if(!/\/today\/?(?:index\.html)?$/.test(location.pathname)) return;
 const state={assessments:null,evidence:null};
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function hrefFor(e){if(e.url)return e.url;if(e.doi)return 'https://doi.org/'+encodeURIComponent(e.doi);if(e.pmid)return 'https://pubmed.ncbi.nlm.nih.gov/'+encodeURIComponent(e.pmid)+'/';return ''}
 function labelType(t){return ({peer_reviewed:'동료심사 논문',field_observation_paper:'현장 관찰 논문',specialist_group_species_account:'전문가 종 계정',specialist_husbandry:'전문 사육자료',specialist_veterinary_review:'전문 수의학 자료',specialist_plant_database:'전문 식물 DB',official_database:'공식 DB',official_agriculture_database:'공식 농업 DB',official_biodiversity_agriculture:'공공 생물·농업 DB',conference_proceedings:'학술대회 자료',peer_reviewed_context:'동료심사 문헌 맥락'}[t]||t||'출처')}
 function applicabilityBadge(e){const s=e.scope||'',t=e.taxon||'';if(s==='subspecies_direct_wild_diet'&&/Testudo graeca ibera/i.test(t))return['적용','이베라 직접 야생근거','direct'];if(s==='subspecies_direct_diet_synthesis'&&/Testudo graeca ibera/i.test(t))return['적용','이베라 종계정 종합','direct'];if(s==='species_direct'||s==='species_diet_context')return['적용','다른 Testudo 직접·맥락','near'];if(s==='genus_husbandry'||s==='Mediterranean_Testudo')return['적용','Testudo·지중해 사육근거','near'];if(s==='plant_identity'||s==='plant_identity_context')return['적용','식물동정 근거','identity'];if(s==='nutrition')return['적용','영양성분 자료','nutrition'];if(e.type==='specialist_husbandry'||e.type==='specialist_veterinary_review'||e.type==='specialist_plant_database')return['적용','전문 사육·식물 근거','specialist'];return['적용','간접·일반 근거','general']}
 function qualityBadge(e){if(['peer_reviewed','field_observation_paper','peer_reviewed_context'].includes(e.type))return['출처','학술문헌','q1'];if(e.type==='specialist_group_species_account')return['출처','전문가 종 계정','q1'];if(['official_database','official_agriculture_database','official_biodiversity_agriculture'].includes(e.type))return['출처','공식·공공 DB','q2'];if(['specialist_husbandry','specialist_veterinary_review','specialist_plant_database'].includes(e.type))return['출처','전문기관 자료','q2'];if(e.type==='conference_proceedings')return['출처','학술대회 자료','q3'];return['출처','기타 출처','q3']}
 function badgeHTML(b){return '<span class="source-badge '+esc(b[2])+'"><span>'+esc(b[0])+'</span> '+esc(b[1])+'</span>'}
 function plantIdFrom(details){const a=details.querySelector('a[href*="../plant/"]');if(!a)return'';const m=a.getAttribute('href').match(/\.\.\/plant\/([^/]+)\//);return m?decodeURIComponent(m[1]):''}
 function renderSource(e){const href=hrefFor(e),tax=e.taxon?' · '+esc(e.taxon):'',badges=badgeHTML(applicabilityBadge(e))+badgeHTML(qualityBadge(e));return '<div class="source-preview-item"><div class="source-badges">'+badges+'</div><b>'+esc(labelType(e.type))+tax+'</b><div>'+esc(e.citation||e.id)+'</div>'+(e.note?'<div class="source-note">'+esc(e.note)+'</div>':'')+(href?'<a href="'+esc(href)+'" target="_blank" rel="noopener noreferrer">원문/식별자 열기 ↗</a>':'')+'</div>'}
 function enhanceOne(details){if(details.dataset.sourcePreview==='1'||!state.assessments||!state.evidence)return;const id=plantIdFrom(details);if(!id)return;const a=state.assessments.find(x=>x.plant_id===id && Array.isArray(x.evidence_ids));if(!a)return;const srcs=a.evidence_ids.map(eid=>state.evidence.find(e=>e.id===eid)).filter(Boolean).slice(0,2);const box=document.createElement('div');box.className='source-preview';box.innerHTML='<div class="source-preview-title"><b>대표 출처 미리보기</b><span> · 최대 2개</span></div>'+(srcs.length?srcs.map(renderSource).join(''):'<div class="source-note">연결된 공개 출처 메타데이터 없음</div>')+'<div class="source-note">배지는 ‘출처의 성격’과 ‘현재 거북에 대한 적용 거리’를 분리해 보여준다. 이 미리보기만으로 전체 판정을 재계산하지 않는다.</div>';details.appendChild(box);details.dataset.sourcePreview='1'}
 function enhanceAll(){document.querySelectorAll('details.evidence').forEach(enhanceOne)}
 function addStyle(){if(document.getElementById('source-preview-style'))return;const s=document.createElement('style');s.id='source-preview-style';s.textContent='.source-preview{margin-top:10px;padding-top:8px;border-top:1px dashed #ccd9cf}.source-preview-title{font-size:13px;margin-bottom:6px}.source-preview-title span,.source-note{font-size:12px;color:#657067}.source-preview-item{padding:8px 0;border-top:1px solid #edf1ed;font-size:12px}.source-preview-item:first-of-type{border-top:0}.source-preview-item a{display:inline-block;margin-top:4px;font-weight:700}.source-preview-item b{font-size:12px}.source-badges{display:flex;gap:5px;flex-wrap:wrap;margin-bottom:5px}.source-badge{display:inline-flex;gap:4px;align-items:center;border:1px solid #d7e0d8;border-radius:999px;padding:2px 7px;font-size:11px;font-weight:800;background:#fff}.source-badge span{font-weight:600;color:#657067}.source-badge.direct{background:#e6f5e9}.source-badge.near,.source-badge.specialist{background:#eef4ff}.source-badge.identity{background:#f4efff}.source-badge.nutrition{background:#fff4e5}.source-badge.general,.source-badge.q3{background:#f5f5f5}.source-badge.q1{background:#eaf7ef}.source-badge.q2{background:#f1f6ff}';document.head.appendChild(s)}
 Promise.all([fetch('../data/assessments.json').then(r=>r.json()),fetch('../data/evidence.json').then(r=>r.json())]).then(([a,e])=>{state.assessments=Array.isArray(a)?a:[];state.evidence=Array.isArray(e)?e:[];addStyle();enhanceAll();new MutationObserver(enhanceAll).observe(document.body,{childList:true,subtree:true})}).catch(()=>{});
})();
